services:
    stack:
        container_name: stack
        restart: always
        working_dir: /var/www/html
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - stack
        depends_on:
            - postgres
            - redis
            - soketi
    postgres:
        image: postgres:15-alpine
        container_name: stack-db
        restart: always
        networks:
            - stack
    redis:
        image: redis:7-alpine
        container_name: stack-redis
        restart: always
        networks:
            - stack
    soketi:
        container_name: stack-realtime
        extra_hosts:
            - host.docker.internal:host-gateway
        restart: always
        networks:
            - stack
networks:
    stack:
        name: stack
        driver: bridge
        external: false
